<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = DB::table('categories')->pluck('id', 'name');
        $suppliers = DB::table('suppliers')->pluck('id', 'name');

        DB::table('products')->insert([
            
            // ===== BAGIAN PRODUK ACTION FIGURE =====
            [
                'code' => 'FIG-NAR-001',
                'name' => 'Nendoroid Naruto Uzumaki',
                'category_id' => $categories['Action Figure'],
                'supplier_id' => $suppliers['AnimeShop Indonesia'],
                'purchase_price' => 500000,
                'selling_price' => 850000,
                'stock' => 15,
                'min_stock' => 3,
                'description' => 'Action figure Naruto dari seri Nendoroid dengan aksesoris Rasengan dan ramen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FIG-GOK-002',
                'name' => 'S.H.Figuarts Goku Ultra Instinct',
                'category_id' => $categories['Action Figure'],
                'supplier_id' => $suppliers['Wibu Store Jakarta'],
                'purchase_price' => 650000,
                'selling_price' => 1100000,
                'stock' => 8,
                'min_stock' => 2,
                'description' => 'Goku Ultra Instinct versi S.H.Figuarts dengan efek aura.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FIG-LUF-003',
                'name' => 'One Piece Portrait of Pirates Luffy Gear 5',
                'category_id' => $categories['Action Figure'],
                'supplier_id' => $suppliers['AnimeShop Indonesia'],
                'purchase_price' => 750000,
                'selling_price' => 1350000,
                'stock' => 5,
                'min_stock' => 1,
                'description' => 'Luffy Gear 5 dari seri Portrait of Pirates ukuran 1/8.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FIG-GOJ-004',
                'name' => 'Nendoroid Gojo Satoru',
                'category_id' => $categories['Action Figure'],
                'supplier_id' => $suppliers['Otaku Merchandise'],
                'purchase_price' => 450000,
                'selling_price' => 780000,
                'stock' => 12,
                'min_stock' => 3,
                'description' => 'Nendoroid Gojo dari Jujutsu Kaisen dengan kacamata hitam dan efek domain.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FIG-MIK-005',
                'name' => 'Hatsune Miku Figure 1/7',
                'category_id' => $categories['Action Figure'],
                'supplier_id' => $suppliers['Otaku Merchandise'],
                'purchase_price' => 900000,
                'selling_price' => 1550000,
                'stock' => 3,
                'min_stock' => 1,
                'description' => 'Hatsune Miku figure ukuran 1/7 dari seri Vocaloid.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK MANGA =====
            [
                'code' => 'MNG-OP-006',
                'name' => 'One Piece Volume 109 - Egghead',
                'category_id' => $categories['Manga'],
                'supplier_id' => $suppliers['Manga Importir'],
                'purchase_price' => 30000,
                'selling_price' => 45000,
                'stock' => 50,
                'min_stock' => 10,
                'description' => 'Volume terbaru One Piece arc Egghead.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MNG-JJK-007',
                'name' => 'Jujutsu Kaisen Volume 24',
                'category_id' => $categories['Manga'],
                'supplier_id' => $suppliers['Manga Importir'],
                'purchase_price' => 28000,
                'selling_price' => 42000,
                'stock' => 35,
                'min_stock' => 8,
                'description' => 'Volume 24 manga Jujutsu Kaisen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MNG-DS-008',
                'name' => 'Demon Slayer Volume 23 - Final',
                'category_id' => $categories['Manga'],
                'supplier_id' => $suppliers['Manga Importir'],
                'purchase_price' => 25000,
                'selling_price' => 38000,
                'stock' => 40,
                'min_stock' => 10,
                'description' => 'Volume final Demon Slayer (Kimetsu no Yaiba).',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK ANIME DVD =====
            [
                'code' => 'DVD-AOT-009',
                'name' => 'Attack on Titan Season 4 Part 3 DVD',
                'category_id' => $categories['Anime DVD'],
                'supplier_id' => $suppliers['Wibu Store Jakarta'],
                'purchase_price' => 120000,
                'selling_price' => 180000,
                'stock' => 10,
                'min_stock' => 2,
                'description' => 'DVD Attack on Titan Season 4 Part 3 dengan subtitle Indonesia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DVD-SPY-010',
                'name' => 'Spy x Family Season 2 DVD',
                'category_id' => $categories['Anime DVD'],
                'supplier_id' => $suppliers['Wibu Store Jakarta'],
                'purchase_price' => 100000,
                'selling_price' => 150000,
                'stock' => 15,
                'min_stock' => 3,
                'description' => 'DVD Spy x Family Season 2 lengkap dengan bonus poster.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK MERCHANDISE =====
            [
                'code' => 'MCH-KEY-011',
                'name' => 'Keychain Miku Hatsune Limited',
                'category_id' => $categories['Merchandise'],
                'supplier_id' => $suppliers['Otaku Merchandise'],
                'purchase_price' => 35000,
                'selling_price' => 65000,
                'stock' => 100,
                'min_stock' => 20,
                'description' => 'Keychain Miku Hatsune edition limited dengan desain eksklusif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MCH-PIN-012',
                'name' => 'Pin Koleksi Jujutsu Kaisen (Set 6)',
                'category_id' => $categories['Merchandise'],
                'supplier_id' => $suppliers['AnimeShop Indonesia'],
                'purchase_price' => 40000,
                'selling_price' => 75000,
                'stock' => 60,
                'min_stock' => 10,
                'description' => 'Set pin karakter Jujutsu Kaisen (Gojo, Yuji, Megumi, Nobara, Sukuna, Maki).',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK POSTER =====
            [
                'code' => 'PST-OP-013',
                'name' => 'Poster One Piece A3 - Straw Hat Crew',
                'category_id' => $categories['Poster'],
                'supplier_id' => $suppliers['Otaku Merchandise'],
                'purchase_price' => 15000,
                'selling_price' => 25000,
                'stock' => 80,
                'min_stock' => 15,
                'description' => 'Poster One Piece ukuran A3 dengan seluruh kru Topi Jerami.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PST-DS-014',
                'name' => 'Poster Demon Slayer A2 - Kimetsu no Yaiba',
                'category_id' => $categories['Poster'],
                'supplier_id' => $suppliers['Otaku Merchandise'],
                'purchase_price' => 25000,
                'selling_price' => 40000,
                'stock' => 50,
                'min_stock' => 10,
                'description' => 'Poster Demon Slayer ukuran A2 dengan desain full color.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK DAKIMAKURA =====
            [
                'code' => 'DK-NEZ-015',
                'name' => 'Dakimakura Nezuko Kamado 160cm',
                'category_id' => $categories['Dakimakura'],
                'supplier_id' => $suppliers['AnimeShop Indonesia'],
                'purchase_price' => 250000,
                'selling_price' => 350000,
                'stock' => 7,
                'min_stock' => 2,
                'description' => 'Dakimakura Nezuko ukuran 160cm dengan bahan premium.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DK-MAI-016',
                'name' => 'Dakimakura Mai Sakurajima 150cm',
                'category_id' => $categories['Dakimakura'],
                'supplier_id' => $suppliers['Wibu Store Jakarta'],
                'purchase_price' => 220000,
                'selling_price' => 320000,
                'stock' => 5,
                'min_stock' => 1,
                'description' => 'Dakimakura Mai Sakurajima dari anime Bunny Girl Senpai.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK GUNDAM =====
            [
                'code' => 'GUN-RX-017',
                'name' => 'Gundam RX-78-2 Model Kit MG',
                'category_id' => $categories['Gundam'],
                'supplier_id' => $suppliers['Gundam Factory'],
                'purchase_price' => 300000,
                'selling_price' => 450000,
                'stock' => 6,
                'min_stock' => 2,
                'description' => 'Master Grade Gundam RX-78-2 original dari Mobile Suit Gundam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GUN-ST-018',
                'name' => 'Gundam Strike Freedom MG',
                'category_id' => $categories['Gundam'],
                'supplier_id' => $suppliers['Gundam Factory'],
                'purchase_price' => 380000,
                'selling_price' => 550000,
                'stock' => 4,
                'min_stock' => 1,
                'description' => 'Master Grade Gundam Strike Freedom dari Gundam SEED Destiny.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BAGIAN PRODUK T-SHIRT =====
            [
                'code' => 'TSH-NAR-019',
                'name' => 'T-Shirt Naruto - Hokage Logo',
                'category_id' => $categories['T-Shirt'],
                'supplier_id' => $suppliers['AnimeShop Indonesia'],
                'purchase_price' => 80000,
                'selling_price' => 120000,
                'stock' => 30,
                'min_stock' => 5,
                'description' => 'Kaos Naruto dengan logo Hokage, bahan cotton premium.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TSH-JJK-020',
                'name' => 'T-Shirt Jujutsu Kaisen - Domain Expansion',
                'category_id' => $categories['T-Shirt'],
                'supplier_id' => $suppliers['Wibu Store Jakarta'],
                'purchase_price' => 85000,
                'selling_price' => 125000,
                'stock' => 25,
                'min_stock' => 5,
                'description' => 'Kaos Jujutsu Kaisen dengan desain Domain Expansion Gojo.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}